=== Turtle5/ktikz/app/tikzcommands.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="tikzcommands">
    <xs:annotation>
      <xs:documentation>
This file should only contain the commands and options defined in Part III "TikZ ist kein Zeichenprogramm" in the PGF Manual.
For ease of maintenance of this file, the structure of Part III of the manual is closely followed here.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="defineLibrary" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="1" minOccurs="0" name="subLibUseCommand" type="xs:string">
                <xs:annotation>
                  <xs:documentation/>
                </xs:annotation>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string">
              <xs:annotation>
                <xs:documentation/>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="subName" type="xs:string" use="optional">
              <xs:annotation>
                <xs:documentation/>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="website" type="xs:string" use="optional">
              <xs:annotation>
                <xs:documentation/>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="depend" maxOccurs="unbounded" minOccurs="0" type="dependency">
          <!--<xs:annotation>
            <xs:documentation></xs:documentation>
          </xs:annotation>-->
        </xs:element>
        <xs:element name="section" maxOccurs="unbounded" minOccurs="0" type="section">
          <!--<xs:annotation>
            <xs:documentation></xs:documentation>
          </xs:annotation>-->
        </xs:element>
      </xs:sequence>
      <xs:attribute name="title" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="dependency">
    <xs:attribute name="on" type="xs:string" use="required">
        </xs:attribute>
  </xs:complexType>
  <xs:complexType name="item">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:string" use="optional">
          <xs:annotation>
            <xs:documentation>human readable name used in the menu or dock widget</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="description" type="xs:string" use="optional">
          <xs:annotation>
            <xs:documentation>is shown in the completion popup and in the statusbar (and is also used for the completion)</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="insert" type="xs:string" use="optional">
          <xs:annotation>
            <xs:documentation>string which is inserted when selected in the menu or dock widget</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="type" type="xs:byte" use="optional">
          <xs:annotation>
            <xs:documentation>type: the highlighting color/font/style depends on the type
              0: plain text (no highlighting)
              1: command
              2: draw to next point
              3: option</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="dx" type="xs:byte" use="optional">
          <xs:annotation>
            <xs:documentation>where the text editing cursor is put after inserting the string, relative to the start of the inserted string
</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="dy" type="xs:byte" use="optional">
          <xs:annotation>
            <xs:documentation>where the text editing cursor is put after inserting the string, relative to the start of the inserted string
</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="highlight" type="xs:string" use="optional">
          <xs:annotation>
            <xs:documentation>human readable name used in the menu or dock widget</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType mixed="true" name="section">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element name="separator">
        <xs:annotation>
          <xs:documentation>A separator</xs:documentation>
        </xs:annotation>
        <xs:complexType>
                </xs:complexType>
      </xs:element>
      <xs:element name="item" type="item">
        <xs:annotation>
          <xs:documentation>An entry</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="section" type="section">
        <xs:annotation>
          <xs:documentation>Subsection</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:choice>
    <xs:attribute name="title" type="xs:string" use="optional"/>
    <xs:attribute name="name" type="xs:string" use="optional"/>
    <xs:attribute name="description" type="xs:string" use="optional"/>
    <xs:attribute name="insert" type="xs:string" use="optional"/>
    <xs:attribute name="type" type="xs:byte" use="optional"/>
  </xs:complexType>
</xs:schema>

=== Turtle5/ktikz/app/tikzcommands.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE tikzcommands>-->
<!--
name: human readable name used in the menu or dock widget
description: is shown in the completion popup and in the statusbar (and is also used for the completion)
insert: string which is inserted when selected in the menu or dock widget
dx, dy: where the text editing cursor is put after inserting the string, relative to the start of the inserted string
type: the highlighting color/font/style depends on the type
 0: plain text (no highlighting)
 1: command
 2: draw to next point
 3: option
This file should only contain the commands and options defined in Part III "TikZ ist kein Zeichenprogramm" in the PGF Manual.
For ease of maintenance of this file, the structure of Part III of the manual is closely followed here.
-->
<tikzcommands
    xmlns="http://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="tikzcommands.xsd"
    title="&amp;Insert">
	<!-- 12 -->
	<section title="Pict&amp;ures, scopes and styles">
		<!-- 12.2 -->
		<item name="&amp;TikZ picture environment" description="\\begin{tikzpicture}[&lt;options&gt;]" insert="\\begin{tikzpicture}\n\n\\end{tikzpicture}" dx="0" dy="1" type="0"/>
		<item name="&amp;Close TikZ picture environment" description="\\end{tikzpicture}" insert="\\end{tikzpicture}" type="0"/>
		<section title="Pict&amp;ures">
			<separator/>
			<item name="&amp;Set baseline" description="baseline=&lt;coordinate/dimension&gt;" insert="baseline=&#8226;" type="3"/>
			<separator/>
			<item name="Install code to be executed at &amp;begin of picture" description="execute at begin picture=&lt;code&gt;" insert="execute at begin picture=&#8226;" type="3"/>
			<item name="Install code to be executed at &amp;end of picture" description="execute at end picture=&lt;code&gt;" insert="execute at end picture=&#8226;" type="3"/>
			<separator/>
			<item name="&amp;Define style for every picture" description="every picture/.style={&lt;style&gt;}" insert="every picture/.style={&#8226;}" type="3"/>
			<item name="&amp;Add to style for every picture" description="every picture/append .style={&lt;style&gt;}" insert="every picture/append .style={&#8226;}" type="3"/>
		</section>
		<section title="&amp;Scopes">
			<item name="&amp;Scope environment" description="\\begin{scope}[&lt;options&gt;]" insert="\\begin{scope}\n\n\\end{scope}" dx="0" dy="1" type="0"/>
			<item name="&amp;Close scope environment" description="\\end{scope}" insert="\\end{scope}" type="0"/>
			<separator/>
			<item name="Install code to be executed at &amp;begin of scope" description="execute at begin scope=&lt;code&gt;" insert="execute at begin scope=&#8226;" type="3"/>
			<item name="Install code to be executed at &amp;end of scope" description="execute at end scope=&lt;code&gt;" insert="execute at end scope=&#8226;" type="3"/>
			<separator/>
			<item name="&amp;Define style for every scope" description="every scope/.style={&lt;style&gt;}" insert="every scope/.style={&#8226;}" type="3"/>
			<item name="&amp;Add to style for every scope" description="every scope/append .style={&lt;style&gt;}" insert="every scope/append .style={&#8226;}" type="3"/>
		</section>
		<section title="&amp;Options">
			<item name="Set &amp;definition" description="\\tikzset{&lt;variable&gt;=&lt;value&gt;}" insert="\\tikzset{&#8226;=&#8226;}" type="1"/>
			<item name="Define c&amp;olor" description="\\colorlet{&lt;name&gt;}{&lt;value&gt;}" insert="\\colorlet{&#8226;}{&#8226;}" type="1"/>
			<separator/>
			<item name="Define s&amp;tyle" description="\\tikzstyle{&lt;name&gt;}=[&lt;options&gt;]" insert="\\tikzstyle{&#8226;}=[&#8226;]" type="1"/>
			<item name="Add to st&amp;yle" description="\\tikzstyle{&lt;name&gt;}+=[&lt;options&gt;]" insert="\\tikzstyle{&#8226;}+=[&#8226;]" type="1"/>
			<item name="Define sty&amp;le (as option)" description="&lt;name&gt;/.style={&lt;style&gt;}" insert="&#8226;/.style={&#8226;}" type="3"/>
			<item name="Add to styl&amp;e (as option)" description="&lt;name&gt;/append .style={&lt;style&gt;}" insert="&#8226;/append .style={&#8226;}" type="3"/>
		</section>
		<separator/>
		<item name="&amp;Load tikz library" description="\\usetikzlibrary{&lt;library name&gt;}" insert="\\usetikzlibrary{&#8226;}" type="1"/>
	</section>
	<section title="&amp;Loops">
		<item name="&amp;For-loop" description="\\foreach &lt;variable&gt; in {&lt;list&gt;}" insert="\\foreach &#8226; in {&#8226;}" type="1"/>
		<item name="For-loop with &amp;iteration" description="\\foreach \\x in {&lt;first&gt;,&lt;first+step&gt;,...,&lt;last&gt;}" insert="\\foreach \\x in {&#8226;,&#8226;,...,&#8226;}" type="1"/>
		<item name="For-loop with &amp;custom text" description="\\foreach \\x/\\xtext in {&lt;value1&gt;/&lt;text1&gt;,&lt;value2&gt;/&lt;text2&gt;}" insert="\\foreach \\x/\\xtext in {&#8226;/&#8226;,&#8226;/&#8226;}" type="1"/>
		<item name="&amp;Break out from for-loop" description="\\breakforeach" insert="\\breakforeach" type="1"/>
		<separator/>
		<item description="\\ifnum" insert="\\ifnum" type="1"/>
	</section>
	<!-- 13 -->
	<section title="Specifying &amp;coordinates">
<!-- TODO complete this -->
		<item name="&amp;Absolute point" description="(&lt;xcoord&gt;,&lt;ycoord&gt;)" insert="(&#8226;,&#8226;)" type="0"/>
		<item name="Point &amp;relative to reference point (keep reference point)" description="+(&lt;xcoord&gt;,&lt;ycoord&gt;)" insert="+(&#8226;,&#8226;)" type="0"/>
		<item name="Point relative to reference point (&amp;update reference point)" description="++(&lt;xcoord&gt;,&lt;ycoord&gt;)" insert="++(&#8226;,&#8226;)" type="0"/>
		<item name="&amp;Polar coordinates" description="(&lt;degree&gt;:&lt;radius&gt;)" insert="(&#8226;:&#8226;)" type="0"/>
		<item name="&amp;Intersection of two lines" description="(intersection of &lt;x1&gt;,&lt;y1&gt;--&lt;x2&gt;,&lt;y2&gt; and &lt;x3&gt;,&lt;y3&gt;--&lt;x4&gt;,&lt;y4&gt;)" insert="(intersection of &#8226;,&#8226;--&#8226;,&#8226; and &#8226;,&#8226;--&#8226;,&#8226;)" highlight="intersection of" type="2"/>
	</section>
	<!-- 14 -->
	<section title="&amp;Path specifications">
		<item name="Define &amp;path" description="\\path" insert="\\path ;" type="1"/>
		<section title="St&amp;yles">
			<item name="Define style for every path (&amp;standalone)" description="\\tikzstyle{every path}=[&lt;options&gt;]" insert="\\tikzstyle{every path}=[&#8226;]" type="0"/>
			<item name="Define style for every path (as &amp;option)" description="every path/.style={&lt;style&gt;}" insert="every path/.style={&#8226;}" type="3"/>
			<item name="Add to style for every path (s&amp;tandalone)" description="\\tikzstyle{every path}+=[&lt;options&gt;]" insert="\\tikzstyle{every path}+=[&#8226;]" type="0"/>
			<item name="Add to style for every path (as o&amp;ption)" description="every path/append .style={&lt;style&gt;}" insert="every path/append .style={&#8226;}" type="3"/>
		</section>
		<!-- 14.1 -->
		<section title="&amp;Move to">
			<item name="Move to &amp;point" description="&lt;end point&gt;" insert=" (&#8226;,&#8226;)" type="0"/>
			<item name="Move to &amp;relative point (keep reference point)" description="+&lt;end point&gt;" insert=" +(&#8226;,&#8226;)" type="0"/>
			<item name="Move to r&amp;elative point (update reference point)" description="++&lt;end point&gt;" insert=" ++(&#8226;,&#8226;)" type="0"/>
		</section>
		<!-- 14.2, 14.4 -->
		<section title="&amp;Line to">
			<item name="&amp;Line to" description="-- &lt;end point&gt;" insert=" -- (&#8226;,&#8226;)" highlight=" --(?=\s*\()" type="2"/>
			<item name="Line to &amp;relative point (keep reference point)" description="-- +&lt;end point&gt;" insert=" -- +(&#8226;,&#8226;)" highlight=" --(?=\s*\+\()" type="2"/>
			<item name="Line to rela&amp;tive point (update reference point)" description="-- ++&lt;end point&gt;" insert=" -- ++(&#8226;,&#8226;)" highlight=" --(?=\s*\+\+\()" type="2"/>
			<item name="Line to &amp;node" description="-- (&lt;label&gt;)" insert=" -- (&#8226;)" highlight=" .. (?=\s*\+*\()" type="2"/>
			<item name="Line to node with &amp;anchor" description="-- (&lt;label&gt;.&lt;north/south/...&gt;) " insert=" -- (&#8226;.&#8226;)" type="0"/>
			<item name="&amp;Edge to (&quot;to&quot; with its own options)" description="edge[&lt;options&gt;] &lt;end point&gt;" insert=" edge[&#8226;] (&#8226;,&#8226;)" highlight=" edge(?=\s*(\[|\())" type="2"/>
			<item name="C&amp;ycle" description="-- cycle" insert=" -- cycle" type="2"/>
			<separator/>
			<item name="First &amp;horizontal, then vertical" description="-| &lt;end point&gt;" insert=" -| &#8226;,&#8226;" highlight="-\|" type="2"/>
			<item name="First &amp;vertical, then horizontal" description="|- &lt;end point&gt;" insert=" |- &#8226;,&#8226;" highlight="\|-" type="2"/>
		</section>
		<!-- 14.3 -->
		<section title="&amp;Curves">
			<item name="C&amp;urve to (specify angles)" description="to[out=&lt;degree&gt;,in=&lt;degree&gt;] &lt;end point&gt;" insert=" to[out=&#8226;,in=&#8226;] (&#8226;,&#8226;)" type="0"/>
			<item name="Cur&amp;ve to (specify control points)" description=".. controls &lt;ctrl1&gt; and &lt;ctrl2&gt; .. &lt;end point&gt;" insert=" .. controls (&#8226;,&#8226;) and (&#8226;,&#8226;) .. (&#8226;,&#8226;)" highlight=".. controls" type="2"/>
		</section>
		<separator/>
		<!-- 14.5 -->
		<section title="&amp;Rectangle">
			<item name="&amp;Rectangle" description="rectangle &lt;corner&gt;" insert=" rectangle (&#8226;,&#8226;)" highlight=" rectangle(?=\s*\+*\()" type="2"/>
			<separator/>
			<item name="&amp;Define style for every rectangle (standalone)" description="\\tikzstyle{every rectangle}=[&lt;options&gt;]" insert="\\tikzstyle{every rectangle}=[&#8226;]" type="0"/>
			<item name="De&amp;fine style for every rectangle (as option)" description="every rectangle/.style={&lt;style&gt;}" insert="every rectangle/.style={&#8226;}" type="3"/>
